export type DomainErrorCode =
  | "ACTIVITY_INVALID"
  | "ACTIVITY_ID_REQUIRED"
  | "ACTIVITY_USER_ID_REQUIRED"
  | "ACTIVITY_TITLE_REQUIRED"
  | "ACTIVITY_DATE_REQUIRED"
  | "ACTIVITY_DATE_INVALID"
  | "ACTIVITY_TIME_INVALID"
  | "ACTIVITY_CREATED_AT_REQUIRED"
  | "ACTIVITY_UPDATED_AT_REQUIRED"
  | "ACTIVITY_COMPLETED_AT_REQUIRED"
  | "ACTIVITY_STEPS_REQUIRED"
  | "ACTIVITY_STEPS_INVALID"
  | "ACTIVITY_STEP_INVALID"
  | "ACTIVITY_STEP_ID_REQUIRED"
  | "ACTIVITY_STEP_COMPLETED_AT_REQUIRED"
  | "ACTIVITY_STEP_DESCRIPTION_REQUIRED"
  | "ACTIVITY_STEP_ORDER_INVALID"
  | "ACTIVITY_STEP_IDS_DUPLICATED"
  | "ACTIVITY_STEP_ORDERS_DUPLICATED"
  | "ACTIVITY_STEP_NOT_FOUND"
  | "USER_PROFILE_ID_REQUIRED"
  | "USER_PROFILE_NAME_REQUIRED"
  | "USER_PROFILE_CREATED_AT_REQUIRED"
  | "USER_PROFILE_UPDATED_AT_REQUIRED"
  | "ACCESSIBILITY_FONT_SIZE_INVALID"
  | "ACCESSIBILITY_CONTRAST_INVALID"
  | "ACCESSIBILITY_SPACING_INVALID"
  | "ACCESSIBILITY_INTERFACE_MODE_INVALID"
  | "ACCESSIBILITY_ENHANCED_FEEDBACK_INVALID"
  | "ACCESSIBILITY_CONFIRM_CRITICAL_ACTIONS_INVALID"
  | "ACCESSIBILITY_USER_ID_REQUIRED";

export class DomainError extends Error {
  constructor(
    public readonly code: DomainErrorCode,
    message = code,
  ) {
    super(message);
    this.name = "DomainError";
  }
}
